
services:
  postgres:
    image: postgres:14
    container_name: concrete_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: concrete_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./config:/app/config
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres

  dashboard:
    build:
      context: .
      dockerfile: docker/dashboard/Dockerfile
    container_name: concrete_dashboard
    restart: always
    env_file:
    - .env
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./config:/app/config
    depends_on:
      - api

volumes:
  pg_data:
